language: ruby
rvm:
  - 2.7.0
services:
- docker
before_install:
- docker build .
script:
- bundle exec ruby test/test_parser.rb
- bundle exec ruby test/test_rule_matcher.rb
- bundle exec ruby test/test_decorater.rb
